# Generated by Django 5.1.3 on 2024-11-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.CharField(max_length=225, verbose_name='Название рецепта')),
                ('name_ingredients', models.TextField(verbose_name='Название ингридентов')),
                ('instructions', models.TextField(verbose_name='Инструкции')),
                ('cooking_time', models.TextField(verbose_name='Время приголовления')),
                ('status', models.BooleanField(default=False, verbose_name='Веганское ли блюдо?')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
